### ISSUE TITLE
Checklist for missing items in the aiida 1.0 migration

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#266]
- [x] Compare contents of output nodes from parsers -- *See #209*
- [ ] `NamelistsCalculation` and subclasses: restore use_parent_calculation() -- *See #279. MB: I would say that this is not a priority*
- [ ] `NamelistsCalculation`: test code paths in `prepare_for_submission()` when `self.inputs.parent_folder` is a `FolderData` (especially with deep relative paths) or a `SinglefileData`. -- *See #308 for `FolderData`; `SinglefileData` is exercised by `MatdynCalculation` which takes a `ForceconstantsData`.*
- [ ] Documentation: mark down the changes that need to be done to these pages: [code_plugin_int_sum](https://aiida-core.readthedocs.io/en/stable/developer_guide/devel_tutorial/code_plugin_int_sum.html) and [code_plugin_qe](https://aiida-core.readthedocs.io/en/stable/developer_guide/devel_tutorial/code_plugin_qe.html)
- [ ] Harmonize exit codes -- *See #296*
- [ ] In `aiida_quantumespresso/cli/calculations/pw2wannier90.py`, can we set parameters scdm_proj and scdm_entanglement according to the input nnkp file?

**Comment by borellim** [comment]
All items have a separate issue: closing this and removing it from the project.
